export const FETCH_BORROWINGS_REQUEST = 'FETCH_BORROWINGS_REQUEST';
export const FETCH_BORROWINGS_SUCCESS = 'FETCH_BORROWINGS_SUCCESS';
export const FETCH_BORROWINGS_FAILURE = 'FETCH_BORROWINGS_FAILURE';