export const MODAL_BOOKS_OPEN = 'MODAL_BOOKS_OPEN';
export const MODAL_BOOKS_CLOSE = 'MODAL_BOOKS_CLOSE';
export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';
export const SAVE_BOOKS_REQUEST = 'SAVE_BOOKS_REQUEST';
export const SAVE_BOOKS_SUCCESS = 'SAVE_BOOKS_SUCCESS';
export const SAVE_BOOKS_FAILURE = 'SAVE_BOOKS_FAILURE';